<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>


<?php
$db_name = 'mysql:host=localhost;dbname=ClickOnCake';
$user_name = 'root';
$user_password = '770200288';

$conn = mysqli_connect("localhost" , "root" , "7709200288" , "ClickOnCake");

if(isset($_POST['submit'])){

   $name = $_POST['name'];
   $name = filter_var($name, FILTER_SANITIZE_STRING);
   $email = $_POST['email'];
   $email = filter_var($email, FILTER_SANITIZE_STRING);
   $number = $_POST['contact'];
   $number = filter_var($number, FILTER_SANITIZE_STRING);
   $address = $_POST['address'];
   $address = filter_var($address, FILTER_SANITIZE_STRING);
   $prodID = $_POST['prodid'];
   $prodID = filter_var($prodID, FILTER_SANITIZE_STRING);
   $amount = $_POST['amount'];
   $amount = filter_var($amount, FILTER_SANITIZE_STRING);
   $api_key = "rzp_test_FyCOXdWzhiK5zq";
   $count = mysqli_query($conn , "insert into payment values( '$name' , '$email' , '$number','$address','$prodID','$amount')");
        if($count>=1) {
           echo "<script> alert('Sent successfully'); </script>" ;
           include("checkout.html");
        }
}

?>
<form action="checkout.html" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $api_key; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $amount * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id=""// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Click On cake"
    data-description="test payment"
    data-image=""
    data-prefill.name="<?php echo $_POST['name']; ?>"
    data-prefill.email="<?php echo $_POST['email']; ?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>


</body>
</html>